Add if step

diff --git a/.github/workflows/workflow-test.yml b/.github/workflows/workflow-test.yml
--- a/.github/workflows/workflow-test.yml
+++ b/.github/workflows/workflow-test.yml
@@ -13,12 +13,14 @@ jobs: # Steps in a job are ran in sequential order. Multiple jobs are run concur
       - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
       - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
       - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
-      - run: exit 1
+      - run: exit 1 # exit code 1 means the process failed. On fail subsequents steps are NOT run
       - name: Check out repository code
         uses: actions/checkout@v4 # Readymade action: https://github.com/actions/checkout/tree/v4/
         # Find more readymade actions from GitHub Marketplace: https://github.com/marketplace?type=actions
       - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
-      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
+        # with if: always() the following step is always run
+      - if: always()
+        run: echo "🖥️ The workflow is now ready to test your code on the runner."
       - name: List files in the repository
         run: |
           ls ${{ github.workspace }}
